spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-request-size: 4096MB
#  端口号
server:
  port: 1314
  address: 0.0.0.0
